import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar/NavBar";
import Footer from "./components/Footer/Footer";
import PreferencesProvider from "./contexts/PreferencesContext/PreferencesProvider";
import { COPYRIGHT_LOGO_URL } from "./constants/data/data";
import LanguageSelector from "./components/LanguageSelector/LanguageSelector";

export const metadata: Metadata = {
  title: "Portfolio | Harold Rodriguez",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={COPYRIGHT_LOGO_URL} />
      </head>
      <body>
        <div className="min-h-screen bg-gradient-to-br from-blue-950/50 via-slate-950 to-slate-950">
          <PreferencesProvider>
            <NavBar />
            {children}
            <LanguageSelector />
            <Footer />
          </PreferencesProvider>
        </div>
      </body>
    </html>
  );
}
